services:
  - type: web
    name: resume-bot
    env: python
    runtime: python311          # 👈 Force supported version
    startCommand: python main.py
    buildCommand: ""
    envVars:
      - key: TELEGRAM_TOKEN
        value: 7933453858:AAEZAHEZ6PbsEM3ZGVKaX1AGJFoPodF8A8Q
